name: "🐛 Bug Report"
description: Create a report to help us improve the Longitudinal Depression Trajectories Toolkit.
title: "🐛 [BUG] - <title>"
labels:
  - "bug"
assignees:
  - "simonprovost"
body:
  - type: markdown
    attributes:
      value: |
        <div align="center">
           <h1 align="center">
              <br>
              <img src="https://raw.githubusercontent.com/OWNER/REPO/main/public/logo/logo.png" alt="Longitudinal Depression Trajectories Toolkit" width="200">
              <br>
              Longitudinal Depression Trajectories Toolkit
              <br>
           </h1>
           <h4 align="center">
              Toolkit for Longitudinal Depression Trajectories Studies
              <br>
              Millennium Cohort Study (MCS) as Proof-of-Concept —
              <a href="https://github.com">Documentation</a>
           </h4>
        </div>

        <div align="center">
        <img src="https://img.shields.io/static/v1?label=Python&message=3.10%E2%80%933.12&color=3776AB&style=for-the-badge&logo=python&logoColor=white" alt="Python 3.10-3.12">
        <img src="https://img.shields.io/static/v1?label=UV&message=managed&color=2196F3&style=for-the-badge&logo=UV&logoColor=white" alt="UV managed">
        <img src="https://img.shields.io/static/v1?label=RUFF&message=compliant&color=0F172A&style=for-the-badge&logo=ruff&logoColor=white" alt="RUFF compliant">
        <img src="https://img.shields.io/static/v1?label=pre--commit&message=enabled&color=2E7D32&style=for-the-badge&logo=pre-commit&logoColor=white" alt="pre-commit enabled">
        <img src="https://img.shields.io/static/v1?label=beartype&message=compliant&color=8E24AA&style=for-the-badge" alt="beartype compliant">
        </div>
  - type: checkboxes
    id: checks
    attributes:
      label: "Before Submitting"
      description: Please confirm the following to help us process your issue in a timely manner.
      options:
        - label: I have tried the project on MacOS or Linux (Windows is not fully tested).
          required: true
        - label: I have reproduced this with the current CLI entrypoint (`uv run ldt-toolkit --help`).
          required: false
        - label: I have checked the documentation and existing issues.
          required: true
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: Please give us a detailed description of what's not working as expected.
      placeholder: "Hint: ‘brevity is the soul of wit’, Hamlet — by William Shakespeare"
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction Steps"
      description: Help us squash this bug by providing a step-by-step guide.
      value: |
        1. Navigate to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See the issue unfold
      render: python
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "Expected Behavior"
      description: Tell us what you were expecting when the bug appeared.
      placeholder: "Describe the expected outcome."
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: "Screenshots"
      description: If possible, add some screenshots to help us see what you're seeing.
      placeholder: "Hint: Optional, e.g., image links or descriptions."
    validations:
      required: false
  - type: markdown
    attributes:
      value: "### Environment Information"
  - type: dropdown
    id: os
    attributes:
      label: "Operating System"
      description: What operating system were you using when the bug occurred?
      options:
        - "MacOS"
        - "Linux"
        - "Windows"
        - "Other"
  - type: input
    id: other-os
    attributes:
      label: "Other Operating System"
      description: "Only fill this if you selected 'Other' in the Operating System dropdown."
      placeholder: "e.g., Ubuntu 20.04"
    validations:
      required: false
  - type: input
    id: python-version
    attributes:
      label: "Python Version"
      description: What version of Python are you using?
      placeholder: "e.g., 3.10.14"
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: "Additional Information"
      description: Got more to say? Feel free to provide additional information, including dependencies check (e.g., output of uv pip list).
      placeholder: "... write here ..."
    validations:
      required: false
